# Generated by Django 4.0.3 on 2022-03-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('sex', models.BooleanField()),
                ('address', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=30)),
                ('pollsn', models.IntegerField()),
                ('birth', models.IntegerField()),
                ('pollstatus', models.BooleanField()),
                ('etc', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
