# Generated by Django 4.0.3 on 2022-03-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='lid',
            new_name='iid',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='pollsn',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='pollstatus',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='sex',
        ),
    ]
