# Generated by Django 4.0.3 on 2022-04-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useraccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votername', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('ifvoted', models.BooleanField(default=False)),
                ('voteresult', models.CharField(default='0', max_length=1)),
                ('etc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
