# Generated by Django 4.0.3 on 2022-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logineduseraccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
