# Generated by Django 4.0.3 on 2022-04-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='poll_case',
        ),
    ]
