# Generated by Django 4.0.3 on 2022-04-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_logineduseraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='logineduseraccount',
            name='related_useraccount',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userapp.useraccount'),
        ),
    ]
