# Generated by Django 4.0.3 on 2022-04-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_useraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='nameaddress',
            field=models.CharField(blank=True, default='votername + address', max_length=120, null=True),
        ),
    ]
