# Generated by Django 4.0.3 on 2022-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_useraccount_poll_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='logineduseraccount',
            name='doubleloginedstatus',
            field=models.BooleanField(default=False),
        ),
    ]
