# Generated by Django 4.0.3 on 2022-04-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_useraccount_nameaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='nameaddress',
        ),
    ]
