# Generated by Django 4.0.3 on 2022-04-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_logineduseraccount_doubleloginedstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logineduseraccount',
            name='doubleloginedstatus',
        ),
    ]
