# Generated by Django 4.0.3 on 2022-04-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_logineduserpic_related_loginedaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logineduserpic',
            name='content',
        ),
    ]
