# Generated by Django 4.0.3 on 2022-04-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_useraccount_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='votername',
            new_name='name',
        ),
    ]
