# Generated by Django 4.0.3 on 2022-04-18 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_rename_votername_useraccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 3, 8, 0, 399904), verbose_name='date published'),
        ),
    ]
