# Generated by Django 4.0.3 on 2022-04-26 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_logineduserpic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logineduserpic',
            name='related_loginedaccount',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userapp.logineduseraccount'),
        ),
    ]
