# Generated by Django 4.0.3 on 2022-04-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_logineduserpic_related_loginedaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='voteresult',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
