# Generated by Django 4.0.3 on 2022-04-18 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_useraccount_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 18, 3, 19, 31, 419754), null=True, verbose_name='date published'),
        ),
    ]
