# Generated by Django 4.0.3 on 2022-04-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_useraccount_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
