# Generated by Django 4.0.3 on 2022-04-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_useraccount_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='voting_rights',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
