# Generated by Django 4.0.3 on 2022-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_cases',
            name='poll_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
