# Generated by Django 4.0.3 on 2022-04-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_candidate_votes_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poll_Case_Num', models.CharField(max_length=3)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='candidate',
            new_name='candidate_id',
        ),
        migrations.AddField(
            model_name='votes',
            name='vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
