# Generated by Django 4.0.3 on 2022-04-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_poll_cases_poll_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_cases',
            name='takeendpic',
            field=models.BooleanField(default=False),
        ),
    ]
