# Generated by Django 4.0.3 on 2022-04-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_poll_cases_rename_candidate_votes_candidate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll_cases',
            old_name='Poll_Case_Num',
            new_name='poll_Case_Num',
        ),
        migrations.AddField(
            model_name='candidate',
            name='Poll_Case_id',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.poll_cases'),
        ),
    ]
