# Generated by Django 4.0.3 on 2022-04-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_poll_case_num_poll_cases_poll_case_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='candidate_id',
            new_name='Candidate_id',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='vote',
        ),
        migrations.AddField(
            model_name='poll_cases',
            name='poll_name',
            field=models.CharField(blank=True, default='-1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='votes',
            name='votes',
            field=models.IntegerField(blank=0, default=0, null=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Poll_Case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.poll_cases'),
        ),
    ]
