# Generated by Django 4.0.3 on 2022-04-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_candidate_candidatepic_candidate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_cases',
            name='poll_status',
            field=models.BooleanField(default=True),
        ),
    ]
