# Generated by Django 4.0.3 on 2022-04-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_candidate_votes_delete_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll_cases',
            name='pub_date',
        ),
    ]
