# Generated by Django 4.0.3 on 2022-04-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_poll_cases_poll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='CandidateColor',
            field=models.CharField(default='rgba( , , , )', max_length=25),
        ),
    ]
