# Generated by Django 4.0.3 on 2022-04-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_poll_cases_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll_cases',
            old_name='poll_Case_Num',
            new_name='poll_case_num',
        ),
    ]
