# Generated by Django 4.0.3 on 2022-04-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rename_poll_case_num_poll_cases_poll_case_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_cases',
            name='poll_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
