# Generated by Django 4.0.3 on 2022-04-19 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_poll_cases_poll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_cases',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=0, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Poll_Case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.poll_cases'),
        ),
    ]
