# Generated by Django 4.0.3 on 2022-04-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_poll_cases_pub_date_alter_candidate_poll_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_cases',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
