# Generated by Django 4.0.3 on 2022-04-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_poll_cases_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_cases',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date published'),
        ),
    ]
