# Generated by Django 4.0.3 on 2022-04-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_poll_cases_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_cases',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
