# Generated by Django 4.0.3 on 2022-04-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_poll_cases_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll_cases',
            name='pub_date',
        ),
    ]
